---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Set timezone
  timezone:
    name: "{{ common_timezone }}"
  become: yes

- name: Deploy MOTD
  template:
    src: motd.j2
    dest: /etc/motd
    mode: '0644'
  become: yes
