---
galaxy_info:
  role_name: docker
  author: TrainWithShubham
  description: Install and configure Docker across multiple OS families
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble
    - name: EL
      versions:
        - "9"
    - name: Amazon
      versions:
        - "2023"

dependencies: []
